apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micro-transferdb-pvc
  labels:
    type: local
spec:
  storageClassName: local-storage
  volumeName: micro-transferdb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi